/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.mdd.project.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGithubactionScopeProvider extends DelegatingScopeProvider {
}
