/**
 *
 * $Id$
 */
package uk.ac.kcl.inf.mdd.project.githubaction.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link uk.ac.kcl.inf.mdd.project.githubaction.BranchEvent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BranchEventValidator {
	boolean validate();

	boolean validateBranches(EList<String> value);

	boolean validateTags(EList<String> value);

	boolean validateBranchesIgnore(EList<String> value);

	boolean validateTagsIgnore(EList<String> value);

	boolean validatePaths(EList<String> value);

	boolean validatePathsIgnore(EList<String> value);
}
