/**
 *
 * $Id$
 */
package uk.ac.kcl.inf.mdd.project.githubaction.validation;

import org.eclipse.emf.common.util.EList;

import uk.ac.kcl.inf.mdd.project.githubaction.Env;
import uk.ac.kcl.inf.mdd.project.githubaction.Environment;
import uk.ac.kcl.inf.mdd.project.githubaction.Job;
import uk.ac.kcl.inf.mdd.project.githubaction.RunSetting;
import uk.ac.kcl.inf.mdd.project.githubaction.Step;

/**
 * A sample validator interface for {@link uk.ac.kcl.inf.mdd.project.githubaction.Job}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JobValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateSteps(EList<Step> value);

	boolean validateEnv(EList<Env> value);

	boolean validateRunsOn(String value);

	boolean validateNeeds(EList<Job> value);

	boolean validateEnvironment(Environment value);

	boolean validateOutputs(EList<String> value);

	boolean validateDefaults(EList<RunSetting> value);

	boolean validateIf(String value);

	boolean validateId(String value);
}
