/**
 *
 * $Id$
 */
package uk.ac.kcl.inf.mdd.project.githubaction.validation;

import org.eclipse.emf.common.util.EList;

import uk.ac.kcl.inf.mdd.project.githubaction.Env;
import uk.ac.kcl.inf.mdd.project.githubaction.InputParameter;
import uk.ac.kcl.inf.mdd.project.githubaction.Run;
import uk.ac.kcl.inf.mdd.project.githubaction.RunSetting;

/**
 * A sample validator interface for {@link uk.ac.kcl.inf.mdd.project.githubaction.Step}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StepValidator {
	boolean validate();

	boolean validateEnv(EList<Env> value);

	boolean validateName(String value);

	boolean validateUses(EList<String> value);

	boolean validateRunSetting(RunSetting value);

	boolean validateId(String value);

	boolean validateIf(String value);

	boolean validateRun(Run value);

	boolean validateWith(EList<InputParameter> value);

	boolean validateEntrypoint(String value);

	boolean validateArgs(String value);
}
