/**
 *
 * $Id$
 */
package uk.ac.kcl.inf.mdd.project.githubaction.validation;

import org.eclipse.emf.common.util.EList;

import uk.ac.kcl.inf.mdd.project.githubaction.Env;
import uk.ac.kcl.inf.mdd.project.githubaction.Event;
import uk.ac.kcl.inf.mdd.project.githubaction.Job;
import uk.ac.kcl.inf.mdd.project.githubaction.RunSetting;

/**
 * A sample validator interface for {@link uk.ac.kcl.inf.mdd.project.githubaction.Workflow}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkflowValidator {
	boolean validate();

	boolean validateJobs(EList<Job> value);

	boolean validateOn(EList<Event> value);

	boolean validateName(String value);

	boolean validateEnv(EList<Env> value);

	boolean validateDefaults(RunSetting value);
}
