/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.project.githubaction.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import uk.ac.kcl.inf.mdd.project.githubaction.GithubactionPackage;
import uk.ac.kcl.inf.mdd.project.githubaction.RepositoryDispatchEvent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Repository Dispatch Event</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.project.githubaction.impl.RepositoryDispatchEventImpl#getEventTypes <em>Event Types</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RepositoryDispatchEventImpl extends EventImpl implements RepositoryDispatchEvent
{
  /**
   * The cached value of the '{@link #getEventTypes() <em>Event Types</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEventTypes()
   * @generated
   * @ordered
   */
  protected EList<String> eventTypes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RepositoryDispatchEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GithubactionPackage.Literals.REPOSITORY_DISPATCH_EVENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getEventTypes()
  {
    if (eventTypes == null)
    {
      eventTypes = new EDataTypeEList<String>(String.class, this, GithubactionPackage.REPOSITORY_DISPATCH_EVENT__EVENT_TYPES);
    }
    return eventTypes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GithubactionPackage.REPOSITORY_DISPATCH_EVENT__EVENT_TYPES:
        return getEventTypes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GithubactionPackage.REPOSITORY_DISPATCH_EVENT__EVENT_TYPES:
        getEventTypes().clear();
        getEventTypes().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GithubactionPackage.REPOSITORY_DISPATCH_EVENT__EVENT_TYPES:
        getEventTypes().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GithubactionPackage.REPOSITORY_DISPATCH_EVENT__EVENT_TYPES:
        return eventTypes != null && !eventTypes.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (eventTypes: ");
    result.append(eventTypes);
    result.append(')');
    return result.toString();
  }

} //RepositoryDispatchEventImpl
