/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.project.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.mdd.project.githubaction.xtext.ui.internal.XtextActivator;

public class GithubactionUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("uk.ac.kcl.inf.mdd.project.Githubaction");
	}

}
