/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.mdd.project.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GithubactionUiModule extends AbstractGithubactionUiModule {

	public GithubactionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
