/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.mdd.project;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GithubactionStandaloneSetup extends GithubactionStandaloneSetupGenerated {

	public static void doSetup() {
		new GithubactionStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
