/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.project.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uk.ac.kcl.inf.mdd.project.ide.contentassist.antlr.internal.InternalGithubactionParser;
import uk.ac.kcl.inf.mdd.project.services.GithubactionGrammarAccess;

public class GithubactionParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GithubactionGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GithubactionGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEventAccess().getAlternatives(), "rule__Event__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getIssueActivityTypeAccess().getAlternatives(), "rule__IssueActivityType__Alternatives");
			builder.put(grammarAccess.getLabelActivityTypeAccess().getAlternatives(), "rule__LabelActivityType__Alternatives");
			builder.put(grammarAccess.getRepositoryAccess().getGroup(), "rule__Repository__Group__0");
			builder.put(grammarAccess.getRepositoryAccess().getGroup_3(), "rule__Repository__Group_3__0");
			builder.put(grammarAccess.getRepositoryAccess().getGroup_3_3(), "rule__Repository__Group_3_3__0");
			builder.put(grammarAccess.getWorkflowAccess().getGroup(), "rule__Workflow__Group__0");
			builder.put(grammarAccess.getWorkflowAccess().getGroup_3(), "rule__Workflow__Group_3__0");
			builder.put(grammarAccess.getWorkflowAccess().getGroup_4(), "rule__Workflow__Group_4__0");
			builder.put(grammarAccess.getWorkflowAccess().getGroup_4_3(), "rule__Workflow__Group_4_3__0");
			builder.put(grammarAccess.getWorkflowAccess().getGroup_5(), "rule__Workflow__Group_5__0");
			builder.put(grammarAccess.getWorkflowAccess().getGroup_5_3(), "rule__Workflow__Group_5_3__0");
			builder.put(grammarAccess.getWorkflowAccess().getGroup_6(), "rule__Workflow__Group_6__0");
			builder.put(grammarAccess.getWorkflowAccess().getGroup_7(), "rule__Workflow__Group_7__0");
			builder.put(grammarAccess.getWorkflowAccess().getGroup_7_3(), "rule__Workflow__Group_7_3__0");
			builder.put(grammarAccess.getJobAccess().getGroup(), "rule__Job__Group__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3(), "rule__Job__Group_3__0");
			builder.put(grammarAccess.getJobAccess().getGroup_4(), "rule__Job__Group_4__0");
			builder.put(grammarAccess.getJobAccess().getGroup_4_3(), "rule__Job__Group_4_3__0");
			builder.put(grammarAccess.getJobAccess().getGroup_5(), "rule__Job__Group_5__0");
			builder.put(grammarAccess.getJobAccess().getGroup_6(), "rule__Job__Group_6__0");
			builder.put(grammarAccess.getJobAccess().getGroup_7(), "rule__Job__Group_7__0");
			builder.put(grammarAccess.getJobAccess().getGroup_7_3(), "rule__Job__Group_7_3__0");
			builder.put(grammarAccess.getJobAccess().getGroup_8(), "rule__Job__Group_8__0");
			builder.put(grammarAccess.getJobAccess().getGroup_8_3(), "rule__Job__Group_8_3__0");
			builder.put(grammarAccess.getJobAccess().getGroup_9(), "rule__Job__Group_9__0");
			builder.put(grammarAccess.getJobAccess().getGroup_9_3(), "rule__Job__Group_9_3__0");
			builder.put(grammarAccess.getJobAccess().getGroup_10(), "rule__Job__Group_10__0");
			builder.put(grammarAccess.getJobAccess().getGroup_11(), "rule__Job__Group_11__0");
			builder.put(grammarAccess.getJobAccess().getGroup_11_3(), "rule__Job__Group_11_3__0");
			builder.put(grammarAccess.getStepAccess().getGroup(), "rule__Step__Group__0");
			builder.put(grammarAccess.getStepAccess().getGroup_4(), "rule__Step__Group_4__0");
			builder.put(grammarAccess.getStepAccess().getGroup_5(), "rule__Step__Group_5__0");
			builder.put(grammarAccess.getStepAccess().getGroup_6(), "rule__Step__Group_6__0");
			builder.put(grammarAccess.getStepAccess().getGroup_7(), "rule__Step__Group_7__0");
			builder.put(grammarAccess.getStepAccess().getGroup_7_3(), "rule__Step__Group_7_3__0");
			builder.put(grammarAccess.getStepAccess().getGroup_8(), "rule__Step__Group_8__0");
			builder.put(grammarAccess.getStepAccess().getGroup_9(), "rule__Step__Group_9__0");
			builder.put(grammarAccess.getStepAccess().getGroup_9_3(), "rule__Step__Group_9_3__0");
			builder.put(grammarAccess.getStepAccess().getGroup_10(), "rule__Step__Group_10__0");
			builder.put(grammarAccess.getStepAccess().getGroup_11(), "rule__Step__Group_11__0");
			builder.put(grammarAccess.getStepAccess().getGroup_12(), "rule__Step__Group_12__0");
			builder.put(grammarAccess.getStepAccess().getGroup_12_3(), "rule__Step__Group_12_3__0");
			builder.put(grammarAccess.getEnvAccess().getGroup(), "rule__Env__Group__0");
			builder.put(grammarAccess.getInputParameterAccess().getGroup(), "rule__InputParameter__Group__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup(), "rule__Environment__Group__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup_4(), "rule__Environment__Group_4__0");
			builder.put(grammarAccess.getRunSettingAccess().getGroup(), "rule__RunSetting__Group__0");
			builder.put(grammarAccess.getRunSettingAccess().getGroup_3(), "rule__RunSetting__Group_3__0");
			builder.put(grammarAccess.getRunSettingAccess().getGroup_4(), "rule__RunSetting__Group_4__0");
			builder.put(grammarAccess.getRunSettingAccess().getGroup_5(), "rule__RunSetting__Group_5__0");
			builder.put(grammarAccess.getRunSettingAccess().getGroup_5_3(), "rule__RunSetting__Group_5_3__0");
			builder.put(grammarAccess.getPushEventAccess().getGroup(), "rule__PushEvent__Group__0");
			builder.put(grammarAccess.getPushEventAccess().getGroup_3(), "rule__PushEvent__Group_3__0");
			builder.put(grammarAccess.getPushEventAccess().getGroup_3_3(), "rule__PushEvent__Group_3_3__0");
			builder.put(grammarAccess.getPushEventAccess().getGroup_4(), "rule__PushEvent__Group_4__0");
			builder.put(grammarAccess.getPushEventAccess().getGroup_4_3(), "rule__PushEvent__Group_4_3__0");
			builder.put(grammarAccess.getPushEventAccess().getGroup_5(), "rule__PushEvent__Group_5__0");
			builder.put(grammarAccess.getPushEventAccess().getGroup_5_3(), "rule__PushEvent__Group_5_3__0");
			builder.put(grammarAccess.getPushEventAccess().getGroup_6(), "rule__PushEvent__Group_6__0");
			builder.put(grammarAccess.getPushEventAccess().getGroup_6_3(), "rule__PushEvent__Group_6_3__0");
			builder.put(grammarAccess.getPushEventAccess().getGroup_7(), "rule__PushEvent__Group_7__0");
			builder.put(grammarAccess.getPushEventAccess().getGroup_7_3(), "rule__PushEvent__Group_7_3__0");
			builder.put(grammarAccess.getPushEventAccess().getGroup_8(), "rule__PushEvent__Group_8__0");
			builder.put(grammarAccess.getPushEventAccess().getGroup_8_3(), "rule__PushEvent__Group_8_3__0");
			builder.put(grammarAccess.getPullRequestEventAccess().getGroup(), "rule__PullRequestEvent__Group__0");
			builder.put(grammarAccess.getPullRequestEventAccess().getGroup_3(), "rule__PullRequestEvent__Group_3__0");
			builder.put(grammarAccess.getPullRequestEventAccess().getGroup_3_3(), "rule__PullRequestEvent__Group_3_3__0");
			builder.put(grammarAccess.getPullRequestEventAccess().getGroup_4(), "rule__PullRequestEvent__Group_4__0");
			builder.put(grammarAccess.getPullRequestEventAccess().getGroup_4_3(), "rule__PullRequestEvent__Group_4_3__0");
			builder.put(grammarAccess.getPullRequestEventAccess().getGroup_5(), "rule__PullRequestEvent__Group_5__0");
			builder.put(grammarAccess.getPullRequestEventAccess().getGroup_5_3(), "rule__PullRequestEvent__Group_5_3__0");
			builder.put(grammarAccess.getPullRequestEventAccess().getGroup_6(), "rule__PullRequestEvent__Group_6__0");
			builder.put(grammarAccess.getPullRequestEventAccess().getGroup_6_3(), "rule__PullRequestEvent__Group_6_3__0");
			builder.put(grammarAccess.getPullRequestEventAccess().getGroup_7(), "rule__PullRequestEvent__Group_7__0");
			builder.put(grammarAccess.getPullRequestEventAccess().getGroup_7_3(), "rule__PullRequestEvent__Group_7_3__0");
			builder.put(grammarAccess.getPullRequestEventAccess().getGroup_8(), "rule__PullRequestEvent__Group_8__0");
			builder.put(grammarAccess.getPullRequestEventAccess().getGroup_8_3(), "rule__PullRequestEvent__Group_8_3__0");
			builder.put(grammarAccess.getScheduleEventAccess().getGroup(), "rule__ScheduleEvent__Group__0");
			builder.put(grammarAccess.getScheduleEventAccess().getGroup_3(), "rule__ScheduleEvent__Group_3__0");
			builder.put(grammarAccess.getScheduleEventAccess().getGroup_4(), "rule__ScheduleEvent__Group_4__0");
			builder.put(grammarAccess.getScheduleEventAccess().getGroup_5(), "rule__ScheduleEvent__Group_5__0");
			builder.put(grammarAccess.getScheduleEventAccess().getGroup_6(), "rule__ScheduleEvent__Group_6__0");
			builder.put(grammarAccess.getScheduleEventAccess().getGroup_7(), "rule__ScheduleEvent__Group_7__0");
			builder.put(grammarAccess.getWorkflowDispatchEventAccess().getGroup(), "rule__WorkflowDispatchEvent__Group__0");
			builder.put(grammarAccess.getWorkflowDispatchEventAccess().getGroup_3(), "rule__WorkflowDispatchEvent__Group_3__0");
			builder.put(grammarAccess.getWorkflowDispatchEventAccess().getGroup_3_3(), "rule__WorkflowDispatchEvent__Group_3_3__0");
			builder.put(grammarAccess.getRepositoryDispatchEventAccess().getGroup(), "rule__RepositoryDispatchEvent__Group__0");
			builder.put(grammarAccess.getRepositoryDispatchEventAccess().getGroup_3(), "rule__RepositoryDispatchEvent__Group_3__0");
			builder.put(grammarAccess.getRepositoryDispatchEventAccess().getGroup_3_3(), "rule__RepositoryDispatchEvent__Group_3_3__0");
			builder.put(grammarAccess.getCreateEventAccess().getGroup(), "rule__CreateEvent__Group__0");
			builder.put(grammarAccess.getDeleteEventAccess().getGroup(), "rule__DeleteEvent__Group__0");
			builder.put(grammarAccess.getDeploymentEventAccess().getGroup(), "rule__DeploymentEvent__Group__0");
			builder.put(grammarAccess.getIssueEventAccess().getGroup(), "rule__IssueEvent__Group__0");
			builder.put(grammarAccess.getIssueEventAccess().getGroup_3(), "rule__IssueEvent__Group_3__0");
			builder.put(grammarAccess.getIssueEventAccess().getGroup_3_3(), "rule__IssueEvent__Group_3_3__0");
			builder.put(grammarAccess.getLabelEventAccess().getGroup(), "rule__LabelEvent__Group__0");
			builder.put(grammarAccess.getLabelEventAccess().getGroup_3(), "rule__LabelEvent__Group_3__0");
			builder.put(grammarAccess.getLabelEventAccess().getGroup_3_3(), "rule__LabelEvent__Group_3_3__0");
			builder.put(grammarAccess.getInputAccess().getGroup(), "rule__Input__Group__0");
			builder.put(grammarAccess.getInputAccess().getGroup_5(), "rule__Input__Group_5__0");
			builder.put(grammarAccess.getInputAccess().getGroup_6(), "rule__Input__Group_6__0");
			builder.put(grammarAccess.getRepositoryAccess().getWorkflowsAssignment_3_2(), "rule__Repository__WorkflowsAssignment_3_2");
			builder.put(grammarAccess.getRepositoryAccess().getWorkflowsAssignment_3_3_1(), "rule__Repository__WorkflowsAssignment_3_3_1");
			builder.put(grammarAccess.getWorkflowAccess().getNamesAssignment_3_1(), "rule__Workflow__NamesAssignment_3_1");
			builder.put(grammarAccess.getWorkflowAccess().getOnAssignment_4_2(), "rule__Workflow__OnAssignment_4_2");
			builder.put(grammarAccess.getWorkflowAccess().getOnAssignment_4_3_1(), "rule__Workflow__OnAssignment_4_3_1");
			builder.put(grammarAccess.getWorkflowAccess().getEnvAssignment_5_2(), "rule__Workflow__EnvAssignment_5_2");
			builder.put(grammarAccess.getWorkflowAccess().getEnvAssignment_5_3_1(), "rule__Workflow__EnvAssignment_5_3_1");
			builder.put(grammarAccess.getWorkflowAccess().getDefaultsAssignment_6_1(), "rule__Workflow__DefaultsAssignment_6_1");
			builder.put(grammarAccess.getWorkflowAccess().getJobsAssignment_7_2(), "rule__Workflow__JobsAssignment_7_2");
			builder.put(grammarAccess.getWorkflowAccess().getJobsAssignment_7_3_1(), "rule__Workflow__JobsAssignment_7_3_1");
			builder.put(grammarAccess.getJobAccess().getNameAssignment_1(), "rule__Job__NameAssignment_1");
			builder.put(grammarAccess.getJobAccess().getJobNameAssignment_3_1(), "rule__Job__JobNameAssignment_3_1");
			builder.put(grammarAccess.getJobAccess().getNeedsAssignment_4_2(), "rule__Job__NeedsAssignment_4_2");
			builder.put(grammarAccess.getJobAccess().getNeedsAssignment_4_3_1(), "rule__Job__NeedsAssignment_4_3_1");
			builder.put(grammarAccess.getJobAccess().getRunsOnAssignment_5_1(), "rule__Job__RunsOnAssignment_5_1");
			builder.put(grammarAccess.getJobAccess().getEnvironmentAssignment_6_1(), "rule__Job__EnvironmentAssignment_6_1");
			builder.put(grammarAccess.getJobAccess().getOutputsAssignment_7_2(), "rule__Job__OutputsAssignment_7_2");
			builder.put(grammarAccess.getJobAccess().getOutputsAssignment_7_3_1(), "rule__Job__OutputsAssignment_7_3_1");
			builder.put(grammarAccess.getJobAccess().getEnvAssignment_8_2(), "rule__Job__EnvAssignment_8_2");
			builder.put(grammarAccess.getJobAccess().getEnvAssignment_8_3_1(), "rule__Job__EnvAssignment_8_3_1");
			builder.put(grammarAccess.getJobAccess().getDefaultsAssignment_9_2(), "rule__Job__DefaultsAssignment_9_2");
			builder.put(grammarAccess.getJobAccess().getDefaultsAssignment_9_3_1(), "rule__Job__DefaultsAssignment_9_3_1");
			builder.put(grammarAccess.getJobAccess().getIfAssignment_10_1(), "rule__Job__IfAssignment_10_1");
			builder.put(grammarAccess.getJobAccess().getStepsAssignment_11_2(), "rule__Job__StepsAssignment_11_2");
			builder.put(grammarAccess.getJobAccess().getStepsAssignment_11_3_1(), "rule__Job__StepsAssignment_11_3_1");
			builder.put(grammarAccess.getStepAccess().getNameAssignment_2(), "rule__Step__NameAssignment_2");
			builder.put(grammarAccess.getStepAccess().getStepNameAssignment_4_1(), "rule__Step__StepNameAssignment_4_1");
			builder.put(grammarAccess.getStepAccess().getIfAssignment_5_1(), "rule__Step__IfAssignment_5_1");
			builder.put(grammarAccess.getStepAccess().getUsesAssignment_6_1(), "rule__Step__UsesAssignment_6_1");
			builder.put(grammarAccess.getStepAccess().getRunAssignment_7_2(), "rule__Step__RunAssignment_7_2");
			builder.put(grammarAccess.getStepAccess().getRunAssignment_7_3_1(), "rule__Step__RunAssignment_7_3_1");
			builder.put(grammarAccess.getStepAccess().getRunSettingAssignment_8_1(), "rule__Step__RunSettingAssignment_8_1");
			builder.put(grammarAccess.getStepAccess().getWithAssignment_9_2(), "rule__Step__WithAssignment_9_2");
			builder.put(grammarAccess.getStepAccess().getWithAssignment_9_3_1(), "rule__Step__WithAssignment_9_3_1");
			builder.put(grammarAccess.getStepAccess().getEntrypointAssignment_10_1(), "rule__Step__EntrypointAssignment_10_1");
			builder.put(grammarAccess.getStepAccess().getArgsAssignment_11_1(), "rule__Step__ArgsAssignment_11_1");
			builder.put(grammarAccess.getStepAccess().getEnvAssignment_12_2(), "rule__Step__EnvAssignment_12_2");
			builder.put(grammarAccess.getStepAccess().getEnvAssignment_12_3_1(), "rule__Step__EnvAssignment_12_3_1");
			builder.put(grammarAccess.getEnvAccess().getNameAssignment_1(), "rule__Env__NameAssignment_1");
			builder.put(grammarAccess.getEnvAccess().getValueAssignment_3(), "rule__Env__ValueAssignment_3");
			builder.put(grammarAccess.getInputParameterAccess().getNameAssignment_1(), "rule__InputParameter__NameAssignment_1");
			builder.put(grammarAccess.getInputParameterAccess().getValueAssignment_3(), "rule__InputParameter__ValueAssignment_3");
			builder.put(grammarAccess.getEnvironmentAccess().getNameAssignment_2(), "rule__Environment__NameAssignment_2");
			builder.put(grammarAccess.getEnvironmentAccess().getUrlAssignment_4_1(), "rule__Environment__UrlAssignment_4_1");
			builder.put(grammarAccess.getRunSettingAccess().getWorkingDirectoryAssignment_3_1(), "rule__RunSetting__WorkingDirectoryAssignment_3_1");
			builder.put(grammarAccess.getRunSettingAccess().getShellAssignment_4_1(), "rule__RunSetting__ShellAssignment_4_1");
			builder.put(grammarAccess.getRunSettingAccess().getWithAssignment_5_2(), "rule__RunSetting__WithAssignment_5_2");
			builder.put(grammarAccess.getRunSettingAccess().getWithAssignment_5_3_1(), "rule__RunSetting__WithAssignment_5_3_1");
			builder.put(grammarAccess.getPushEventAccess().getBranchesAssignment_3_2(), "rule__PushEvent__BranchesAssignment_3_2");
			builder.put(grammarAccess.getPushEventAccess().getBranchesAssignment_3_3_1(), "rule__PushEvent__BranchesAssignment_3_3_1");
			builder.put(grammarAccess.getPushEventAccess().getTagsAssignment_4_2(), "rule__PushEvent__TagsAssignment_4_2");
			builder.put(grammarAccess.getPushEventAccess().getTagsAssignment_4_3_1(), "rule__PushEvent__TagsAssignment_4_3_1");
			builder.put(grammarAccess.getPushEventAccess().getBranchesIgnoreAssignment_5_2(), "rule__PushEvent__BranchesIgnoreAssignment_5_2");
			builder.put(grammarAccess.getPushEventAccess().getBranchesIgnoreAssignment_5_3_1(), "rule__PushEvent__BranchesIgnoreAssignment_5_3_1");
			builder.put(grammarAccess.getPushEventAccess().getTagsIgnoreAssignment_6_2(), "rule__PushEvent__TagsIgnoreAssignment_6_2");
			builder.put(grammarAccess.getPushEventAccess().getTagsIgnoreAssignment_6_3_1(), "rule__PushEvent__TagsIgnoreAssignment_6_3_1");
			builder.put(grammarAccess.getPushEventAccess().getPathsAssignment_7_2(), "rule__PushEvent__PathsAssignment_7_2");
			builder.put(grammarAccess.getPushEventAccess().getPathsAssignment_7_3_1(), "rule__PushEvent__PathsAssignment_7_3_1");
			builder.put(grammarAccess.getPushEventAccess().getPathsIgnoreAssignment_8_2(), "rule__PushEvent__PathsIgnoreAssignment_8_2");
			builder.put(grammarAccess.getPushEventAccess().getPathsIgnoreAssignment_8_3_1(), "rule__PushEvent__PathsIgnoreAssignment_8_3_1");
			builder.put(grammarAccess.getPullRequestEventAccess().getBranchesAssignment_3_2(), "rule__PullRequestEvent__BranchesAssignment_3_2");
			builder.put(grammarAccess.getPullRequestEventAccess().getBranchesAssignment_3_3_1(), "rule__PullRequestEvent__BranchesAssignment_3_3_1");
			builder.put(grammarAccess.getPullRequestEventAccess().getTagsAssignment_4_2(), "rule__PullRequestEvent__TagsAssignment_4_2");
			builder.put(grammarAccess.getPullRequestEventAccess().getTagsAssignment_4_3_1(), "rule__PullRequestEvent__TagsAssignment_4_3_1");
			builder.put(grammarAccess.getPullRequestEventAccess().getBranchesIgnoreAssignment_5_2(), "rule__PullRequestEvent__BranchesIgnoreAssignment_5_2");
			builder.put(grammarAccess.getPullRequestEventAccess().getBranchesIgnoreAssignment_5_3_1(), "rule__PullRequestEvent__BranchesIgnoreAssignment_5_3_1");
			builder.put(grammarAccess.getPullRequestEventAccess().getTagsIgnoreAssignment_6_2(), "rule__PullRequestEvent__TagsIgnoreAssignment_6_2");
			builder.put(grammarAccess.getPullRequestEventAccess().getTagsIgnoreAssignment_6_3_1(), "rule__PullRequestEvent__TagsIgnoreAssignment_6_3_1");
			builder.put(grammarAccess.getPullRequestEventAccess().getPathsAssignment_7_2(), "rule__PullRequestEvent__PathsAssignment_7_2");
			builder.put(grammarAccess.getPullRequestEventAccess().getPathsAssignment_7_3_1(), "rule__PullRequestEvent__PathsAssignment_7_3_1");
			builder.put(grammarAccess.getPullRequestEventAccess().getPathsIgnoreAssignment_8_2(), "rule__PullRequestEvent__PathsIgnoreAssignment_8_2");
			builder.put(grammarAccess.getPullRequestEventAccess().getPathsIgnoreAssignment_8_3_1(), "rule__PullRequestEvent__PathsIgnoreAssignment_8_3_1");
			builder.put(grammarAccess.getScheduleEventAccess().getMinuteAssignment_3_1(), "rule__ScheduleEvent__MinuteAssignment_3_1");
			builder.put(grammarAccess.getScheduleEventAccess().getHourAssignment_4_1(), "rule__ScheduleEvent__HourAssignment_4_1");
			builder.put(grammarAccess.getScheduleEventAccess().getDayAssignment_5_1(), "rule__ScheduleEvent__DayAssignment_5_1");
			builder.put(grammarAccess.getScheduleEventAccess().getMonthAssignment_6_1(), "rule__ScheduleEvent__MonthAssignment_6_1");
			builder.put(grammarAccess.getScheduleEventAccess().getDayOfWeekAssignment_7_1(), "rule__ScheduleEvent__DayOfWeekAssignment_7_1");
			builder.put(grammarAccess.getWorkflowDispatchEventAccess().getInputsAssignment_3_2(), "rule__WorkflowDispatchEvent__InputsAssignment_3_2");
			builder.put(grammarAccess.getWorkflowDispatchEventAccess().getInputsAssignment_3_3_1(), "rule__WorkflowDispatchEvent__InputsAssignment_3_3_1");
			builder.put(grammarAccess.getRepositoryDispatchEventAccess().getEventTypesAssignment_3_2(), "rule__RepositoryDispatchEvent__EventTypesAssignment_3_2");
			builder.put(grammarAccess.getRepositoryDispatchEventAccess().getEventTypesAssignment_3_3_1(), "rule__RepositoryDispatchEvent__EventTypesAssignment_3_3_1");
			builder.put(grammarAccess.getIssueEventAccess().getActivityTypesAssignment_3_2(), "rule__IssueEvent__ActivityTypesAssignment_3_2");
			builder.put(grammarAccess.getIssueEventAccess().getActivityTypesAssignment_3_3_1(), "rule__IssueEvent__ActivityTypesAssignment_3_3_1");
			builder.put(grammarAccess.getLabelEventAccess().getActivityTypesAssignment_3_2(), "rule__LabelEvent__ActivityTypesAssignment_3_2");
			builder.put(grammarAccess.getLabelEventAccess().getActivityTypesAssignment_3_3_1(), "rule__LabelEvent__ActivityTypesAssignment_3_3_1");
			builder.put(grammarAccess.getInputAccess().getRequiredAssignment_1(), "rule__Input__RequiredAssignment_1");
			builder.put(grammarAccess.getInputAccess().getNameAssignment_3(), "rule__Input__NameAssignment_3");
			builder.put(grammarAccess.getInputAccess().getDescriptionAssignment_5_1(), "rule__Input__DescriptionAssignment_5_1");
			builder.put(grammarAccess.getInputAccess().getDefaultAssignment_6_1(), "rule__Input__DefaultAssignment_6_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GithubactionGrammarAccess grammarAccess;

	@Override
	protected InternalGithubactionParser createParser() {
		InternalGithubactionParser result = new InternalGithubactionParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GithubactionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GithubactionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
