/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.project.githubaction;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete Event</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.mdd.project.githubaction.GithubactionPackage#getDeleteEvent()
 * @model
 * @generated
 */
public interface DeleteEvent extends Event
{
} // DeleteEvent
