/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.mdd.project.githubaction;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Repository</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.project.githubaction.Repository#getWorkflows <em>Workflows</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mdd.project.githubaction.GithubactionPackage#getRepository()
 * @model
 * @generated
 */
public interface Repository extends EObject
{
  /**
   * Returns the value of the '<em><b>Workflows</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.mdd.project.githubaction.Workflow}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Workflows</em>' containment reference list.
   * @see uk.ac.kcl.inf.mdd.project.githubaction.GithubactionPackage#getRepository_Workflows()
   * @model containment="true"
   * @generated
   */
  EList<Workflow> getWorkflows();

} // Repository
