/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mdd.project.githubaction;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Workflow</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.project.githubaction.Workflow#getNames <em>Names</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.project.githubaction.Workflow#getOn <em>On</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.project.githubaction.Workflow#getEnv <em>Env</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.project.githubaction.Workflow#getDefaults <em>Defaults</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.project.githubaction.Workflow#getJobs <em>Jobs</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mdd.project.githubaction.GithubactionPackage#getWorkflow()
 * @model
 * @generated
 */
public interface Workflow extends EObject
{
  /**
   * Returns the value of the '<em><b>Names</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Names</em>' attribute.
   * @see #setNames(String)
   * @see uk.ac.kcl.inf.mdd.project.githubaction.GithubactionPackage#getWorkflow_Names()
   * @model
   * @generated
   */
  String getNames();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdd.project.githubaction.Workflow#getNames <em>Names</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Names</em>' attribute.
   * @see #getNames()
   * @generated
   */
  void setNames(String value);

  /**
   * Returns the value of the '<em><b>On</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.mdd.project.githubaction.Event}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>On</em>' containment reference list.
   * @see uk.ac.kcl.inf.mdd.project.githubaction.GithubactionPackage#getWorkflow_On()
   * @model containment="true"
   * @generated
   */
  EList<Event> getOn();

  /**
   * Returns the value of the '<em><b>Env</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.mdd.project.githubaction.Env}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Env</em>' containment reference list.
   * @see uk.ac.kcl.inf.mdd.project.githubaction.GithubactionPackage#getWorkflow_Env()
   * @model containment="true"
   * @generated
   */
  EList<Env> getEnv();

  /**
   * Returns the value of the '<em><b>Defaults</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Defaults</em>' containment reference.
   * @see #setDefaults(RunSetting)
   * @see uk.ac.kcl.inf.mdd.project.githubaction.GithubactionPackage#getWorkflow_Defaults()
   * @model containment="true"
   * @generated
   */
  RunSetting getDefaults();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdd.project.githubaction.Workflow#getDefaults <em>Defaults</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Defaults</em>' containment reference.
   * @see #getDefaults()
   * @generated
   */
  void setDefaults(RunSetting value);

  /**
   * Returns the value of the '<em><b>Jobs</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.mdd.project.githubaction.Job}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jobs</em>' containment reference list.
   * @see uk.ac.kcl.inf.mdd.project.githubaction.GithubactionPackage#getWorkflow_Jobs()
   * @model containment="true"
   * @generated
   */
  EList<Job> getJobs();

} // Workflow
