/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.mdd.project.ide;


/**
 * Use this class to register ide components.
 */
public class GithubactionIdeModule extends AbstractGithubactionIdeModule {
}
